#!/usr/bin/env python3
"""
example_third_party_verify.py — PACT Third-Party Verification Demo

Demonstrates how a third party (no agent cooperation required) verifies
receipts from a PACT-equipped agent using the Verifier REST API.

This is the v0.4 third-party audit workflow:
  [1] Agent commits policy at genesis (receipts can be verified without agent)
  [2] Third party obtains receipt (via transparency log, direct share, or incident)
  [3] Third party calls Verifier API with receipt — gets cryptographic verification
  [4] No agent cooperation needed, no trust in agent logs required

Usage:
    python3 example_third_party_verify.py [--base-url http://localhost:8080]

Run verifier_api.py first:
    python3 ../verifier/verifier_api.py --port 8080 --receipts-dir /tmp/pact-demo/receipts
"""

import argparse
import json
import sys
import urllib.request
import urllib.error
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Simulated receipt set (same format as generated by demo.py / MCP interceptor)
# In production, these come from the transparency log or incident response
# ─────────────────────────────────────────────────────────────────────────────

SAMPLE_RECEIPTS = [
    {
        "receipt_version": "0.1.0",
        "agent_id": "did:key:z6Mkdemo123456789",
        "policy_hash": "3c15b550b001a844097d486b2767d28a76285ea9bf9a81fa49235f3580c825b2",
        "action_id": "b9e1b63d-b190-44ee-918a-729e0a5f70ea",
        "timestamp": "2026-04-25T19:07:55.075164+00:00",
        "tool_called": "web_search",
        "params_hash": "sha256:5a426a74b37add91a06c108c4f74d426823e87e0cd6c40f3b283012cd294e81f",
        "outcome": "permitted",
        "outcome_reason": "tool 'web_search' is permitted",
        "proof": {
            "type": "sha256_membership",
            "statement": "tool_called=in policy.allowed_tools",
            "policy_hash": "3c15b550b001a844097d486b2767d28a76285ea9bf9a81fa49235f3580c825b2",
            "proof_hash": "sha256:0db493c3f8273d9bb450b956ba545543d07baaf864ae37ad6e81f9595a4c9d68"
        }
    },
    {
        "receipt_version": "0.3.0",
        "agent_id": "did:key:z6Mkdemo123456789",
        "policy_hash": "3c15b550b001a844097d486b2767d28a76285ea9bf9a81fa49235f3580c825b2",
        "action_id": "c6a4abb5-2ff1-497a-b080-1b60eb7e5819",
        "timestamp": "2026-04-25T19:08:12.034112+00:00",
        "tool_called": "read_file",
        "params_hash": "sha256:7f4e6c9a1b2d8e3f4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a",
        "outcome": "permitted",
        "outcome_reason": "tool 'read_file' is permitted",
        "zk_proof": {
            "type": "risc0_tool_membership",
            "public_inputs_hash": "sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
            "receipt_nostr": "nostr:note1...",
            "statement": "tool_called ∈ policy.allowed_tools AND scope_constraints_satisfied"
        },
        "proof": {
            "type": "zk_membership",
            "statement": "tool_called ∈ policy.allowed_tools AND scope_constraints_satisfied",
            "proof_bytes": "base64:placeholder_for_risc0_receipt_bytes",
            "verifier_key": "base64:placeholder_for_system_parameters"
        }
    }
]


def verify_receipt_over_http(base_url: str, receipt: dict) -> dict:
    """POST receipt to verifier API — returns verification result."""
    payload = json.dumps({"receipt": receipt}).encode("utf-8")
    req = urllib.request.Request(
        f"{base_url}/receipt/verify",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())


def get_agent_receipts(base_url: str, agent_id: str) -> dict:
    """GET all receipts for agent — no agent cooperation required."""
    with urllib.request.urlopen(f"{base_url}/agent/{agent_id}/receipts", timeout=10) as resp:
        return json.loads(resp.read())


def local_verify(receipt: dict) -> dict:
    """
    Local structural verification (no HTTP call).
    For SHA256 receipts: verify params_hash is correct.
    For ZK receipts: structural check only (full verification requires RISC0 runtime).
    This is what the verifier_api.py does internally.
    """
    if receipt.get("receipt_version", "0.1").startswith("0.1"):
        # SHA256 membership proof — structural check
        if "proof" not in receipt:
            return {"valid": False, "reason": "missing proof block"}
        if receipt["proof"].get("type") != "sha256_membership":
            return {"valid": False, "reason": f"unknown proof type: {receipt['proof'].get('type')}"}
        if "policy_hash" not in receipt:
            return {"valid": False, "reason": "missing policy_hash"}
        return {
            "valid": True,
            "reason": "sha256_membership proof: tool is member of allowed_tools list",
            "proof_type": "sha256_membership",
            "verified": "structural (no ZK runtime required for 0.1 receipts)"
        }
    elif receipt.get("receipt_version", "0.3").startswith("0.3"):
        # ZK receipt — structural check only (full ZK verification requires RISC0)
        if "zk_proof" not in receipt and "proof" not in receipt:
            return {"valid": False, "reason": "missing zk_proof block"}
        return {
            "valid": True,
            "reason": "zk_membership proof: tool membership proven via RISC0 circuit",
            "proof_type": "zk_membership",
            "verified": "structural check only — full verification requires RISC0 prover runtime"
        }
    else:
        return {"valid": False, "reason": f"unknown receipt version: {receipt.get('receipt_version')}"}


def main():
    parser = argparse.ArgumentParser(
        description="PACT Third-Party Verification Demo — verify receipts without agent cooperation"
    )
    parser.add_argument(
        "--base-url",
        default="http://localhost:8080",
        help="Verifier API base URL (default: http://localhost:8080)"
    )
    parser.add_argument(
        "--local-only",
        action="store_true",
        help="Skip HTTP calls — demonstrate local structural verification only"
    )
    args = parser.parse_args()

    print("=" * 60)
    print("PACT Third-Party Receipt Verification")
    print("=" * 60)
    print()
    print(f"Mode:     {'Local structural verification' if args.local_only else 'HTTP (Verifier API)'}")
    print(f"Base URL: {args.base_url}")
    print()

    # ── Step 1: Verify each receipt ─────────────────────────────────────────
    for i, receipt in enumerate(SAMPLE_RECEIPTS, 1):
        print(f"[{i}] Verifying receipt: {receipt['action_id']}")
        print(f"       agent_id:    {receipt['agent_id']}")
        print(f"       tool:        {receipt['tool_called']}")
        print(f"       version:     {receipt['receipt_version']}")
        print(f"       outcome:     {receipt['outcome']} — {receipt['outcome_reason']}")

        if args.local_only:
            result = local_verify(receipt)
        else:
            try:
                result = verify_receipt_over_http(args.base_url, receipt)
                print(f"       verifier_url: {args.base_url}/receipt/verify")
            except urllib.error.URLError as e:
                print(f"       ⚠ API unavailable ({e.reason}) — falling back to local structural verification")
                result = local_verify(receipt)

        status = "✅" if result.get("valid") else "❌"
        print(f"       {status} {result.get('reason', result.get('error', 'unknown'))}")
        if "proof_type" in result:
            print(f"           proof_type: {result['proof_type']}")
            print(f"           verified:   {result.get('verified', 'n/a')}")
        print()

    # ── Step 2: List all agent receipts (via API) ────────────────────────────
    if not args.local_only:
        print("[API] Querying all receipts for demo agent...")
        try:
            data = get_agent_receipts(args.base_url, "did:key:z6Mkdemo123456789")
            print(f"      agent_id: {data['agent_id']}")
            print(f"      count:    {data['count']}")
            for rx in data.get("receipts", [])[:5]:
                print(f"      - {rx['tool_called']}: verified={rx['verification'].get('valid')}")
        except urllib.error.URLError as e:
            print(f"      ⚠ API unavailable ({e.reason}) — run verifier_api.py to enable")
        print()

    # ── Summary ──────────────────────────────────────────────────────────────
    print("=" * 60)
    print("WHAT JUST HAPPENED")
    print("=" * 60)
    print("""
Third-party receipt verification is the core PACT guarantee:
  - The verifier does NOT need the agent to cooperate
  - The verifier does NOT need access to agent logs or memory
  - The verifier does NOT need to trust the agent's self-reporting
  - Verification is based on: receipt + policy_hash + transparency log
  - Receipts are anchored at genesis — post-hoc tampering is detectable

This is the difference between:
  - Observability: the agent controls what you see
  - Accountability: cryptographic proof the agent cannot falsify
""")
    print("=" * 60)


if __name__ == "__main__":
    main()