"""
PACT v0.5 — FHE Behavioral History Layer

Enables PACT receipts over encrypted agent behavioral histories.
Agents accumulate encrypted tool-call traces; receipts prove policy compliance
against the encrypted trace without revealing it.

Architecture:
    Agent behavioral history (tool calls)
        → encrypt_traces() → FHE ciphertexts (encrypted history)
        → generate_fhe_receipt() → ZK proof over encrypted history
        → PACT receipt references FHE layer, not plaintext trace

The FHE layer closes the metadata channel:
    - ZK receipts prove policy compliance without revealing tool names
    - FHE encryption hides which tools were actually called
    - Together: receipt proves "action was within policy" without disclosing "which action"

Composition with PACT v0.3 (ZK receipts):
    PACT v0.3 receipt: proves tool ∈ committed_policy
    FHE layer: proves trace is consistent with encrypted history
    Combined: proves the entire behavioral sequence is compliant

Why this matters:
    FHE crossed the practical threshold in 2026 — Fhenix mainnet,
    Zama Concrete (Python/sklearn wrapper), KuCoin confirm real deployments
    processing thousands of encrypted ops/sec. The accountability gap this closes:
    encrypted agent behavior must still prove policy compliance. Plaintext receipts
    on encrypted agents are a metadata leak. FHE receipts are the structurally
    correct answer.

Integration:
    from pact.fhe_receipt import FHEHistoryEnvelope, generate_fhe_receipt, verify_fhe_receipt
    from pact.zk_host import verify_zk_receipt  # existing v0.3 verifier

References:
    - Fhenix fhevm: Latticeworks FHE EVM (2026 production)
    - Zama Concrete: TFHE Python/sklearn wrapper (Q2 2026)
    - KuCoin FHE 2026: FHE on encrypted smart contracts
    - PACT v0.3: zk_host.py, zk_receipt_generator.py
"""

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


# ---------------------------------------------------------------------------
# FHE Layer Constants
# ---------------------------------------------------------------------------

PACT_FHE_VERSION = "0.5.0"

# FHE parameter presets (match Zama Concrete TFHE-rs defaults)
FHE_PARAMS = {
    "shortint": {
        "lwe_dimension": 635,
        "glwe_dimension": 1,
        "polynomial_size": 2048,
        "message_modulus": 4,
        "carry_modulus": 4,
        "security_level": 128,
    }
}


# ---------------------------------------------------------------------------
# FHE Encrypted History Envelope
# ---------------------------------------------------------------------------

@dataclass
class FHEHistoryEnvelope:
    """
    Encrypted behavioral history for an agent.

    Produced by: FHE encryption of tool-call trace
    Consumed by: generate_fhe_receipt() — ZK proof over encrypted trace

    The envelope contains:
    - ciphertexts: encrypted tool-call hashes (one per step)
    - commitment: hash commitment to the encrypted trace
    - policy_hash: which policy this trace was run against
    - fhe_params: which FHE parameters were used
    """
    version: str = PACT_FHE_VERSION
    envelope_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    agent_id: str = ""
    policy_hash: str = ""           # Policy this history was generated under
    trace_length: int = 0           # Number of encrypted steps
    ciphertext_hashes: list[str] = field(default_factory=list)  # sha256 of each ciphertext
    trace_commitment: str = ""     # sha256 of serialized ciphertext list
    fhe_params: dict = field(default_factory=lambda: FHE_PARAMS.copy())
    encrypted_metadata: Optional[str] = None  # Encrypted session metadata (if any)


# ---------------------------------------------------------------------------
# FHE Receipt Types
# ---------------------------------------------------------------------------

@dataclass
class FHEReceiptProof:
    """
    The FHE-layer proof attached to a PACT receipt.

    In production this is generated by a FHE-aware ZK circuit
    (Zama Concrete + Halo2 or RISC Zero with FHE extension).
    Currently: stub proof matching the production format.
    """
    proof_type: str            # "fhe_membership" | "stub"
    fhe_params: dict            # FHE params used
    encrypted_trace_hash: str   # Commitment to encrypted trace
    policy_hash: str            # Policy this proves compliance against
    compliance_proof: str       # ZK proof bytes or stub marker
    stub: bool = False          # True if using stub (no real FHE prover)


@dataclass
class FHEReceipt:
    """
    A PACT receipt with FHE behavioral history layer.

    Composes with PACT v0.3 ZK receipts:
    - ZK proof: tool ∈ committed_policy (what tool was called, proven)
    - FHE proof: trace is consistent with encrypted history (that this was the only action)

    The FHE layer ensures:
    - Receipt metadata does not leak which specific tools were called
    - Verifier learns compliance, not behavior
    - The agent's full behavioral trace remains confidential
    """
    version: str = PACT_FHE_VERSION
    receipt_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    issued_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    envelope_id: str = ""       # Links to FHEHistoryEnvelope
    agent_id: str = ""
    policy_hash: str = ""       # Policy this receipt proves compliance against
    trace_length: int = 0        # Number of steps in encrypted history
    zk_receipt_ref: Optional[dict] = None  # Embedded PACT v0.3 ZK receipt (optional)
    fhe_proof: Optional[FHEReceiptProof] = None


# ---------------------------------------------------------------------------
# FHE History Utilities
# ---------------------------------------------------------------------------

def hash_trace_ciphertext(ciphertext: str) -> str:
    """Hash a serialized FHE ciphertext for commitment."""
    return f"sha256:{hashlib.sha256(ciphertext.encode('utf-8')).hexdigest()}"


def build_trace_commitment(ciphertexts: list[str]) -> str:
    """
    Build a hash commitment to an encrypted trace.

    Commitment is order-sensitive: changing the sequence of calls
    changes the commitment. This allows the FHE receipt to prove
    "this specific sequence" rather than just "some sequence of N calls".
    """
    trace_json = json.dumps(ciphertexts, sort_keys=False)
    return f"sha256:{hashlib.sha256(trace_json.encode('utf-8')).hexdigest()}"


def create_fhe_envelope(
    agent_id: str,
    policy_hash: str,
    encrypted_tool_hashes: list[str],
    fhe_params: Optional[dict] = None,
) -> FHEHistoryEnvelope:
    """
    Create an FHE encrypted history envelope.

    Args:
        agent_id: Agent's DID or key identifier
        policy_hash: SHA-256 hash of the policy this trace was generated under
        encrypted_tool_hashes: List of encrypted tool-call hashes (FHE ciphertext strings)
        fhe_params: FHE parameter dict (defaults to Zama TFHE-rs 128-bit security)

    Returns:
        FHEHistoryEnvelope ready for receipt generation
    """
    if fhe_params is None:
        fhe_params = FHE_PARAMS.copy()

    ciphertext_hashes = [hash_trace_ciphertext(ct) for ct in encrypted_tool_hashes]
    trace_commitment = build_trace_commitment(encrypted_tool_hashes)

    return FHEHistoryEnvelope(
        agent_id=agent_id,
        policy_hash=policy_hash,
        trace_length=len(encrypted_tool_hashes),
        ciphertext_hashes=ciphertext_hashes,
        trace_commitment=trace_commitment,
        fhe_params=fhe_params,
    )


# ---------------------------------------------------------------------------
# FHE Receipt Generation
# ---------------------------------------------------------------------------

def generate_fhe_stub_proof(envelope: FHEHistoryEnvelope) -> FHEReceiptProof:
    """
    Generate a stub FHE receipt proof.

    Stub proofs match the production format but use a placeholder
    instead of a real FHE-aware ZK proof. Set FHE_STUB=0 when
    Zama Concrete or equivalent FHE prover is available.

    In production:
    - The FHE prover evaluates the encrypted trace against the policy
    - Produces a ZK proof that the trace is compliant
    - The proof is verifiable without decrypting the trace
    """
    return FHEReceiptProof(
        proof_type="fhe_membership",
        fhe_params=envelope.fhe_params,
        encrypted_trace_hash=envelope.trace_commitment,
        policy_hash=envelope.policy_hash,
        compliance_proof=f"STUB_FHE_PROOF:{uuid.uuid4().hex[:16]}",
        stub=True,
    )


def generate_fhe_receipt(
    envelope: FHEHistoryEnvelope,
    zk_receipt: Optional[dict] = None,
) -> FHEReceipt:
    """
    Generate a PACT receipt with FHE behavioral history layer.

    Args:
        envelope: FHEHistoryEnvelope from create_fhe_envelope()
        zk_receipt: Optional embedded PACT v0.3 ZK receipt dict

    Returns:
        FHEReceipt — FHE-layer receipt composable with PACT v0.3

    Usage:
        # Step 1: Build FHE envelope from encrypted tool-call trace
        envelope = create_fhe_envelope(
            agent_id="did:key:z6Mk...",
            policy_hash="sha256:abc123...",
            encrypted_tool_hashes=[ct1, ct2, ct3],
        )

        # Step 2: Generate FHE receipt
        fhe_receipt = generate_fhe_receipt(envelope, zk_receipt=zk_receipt)

        # Step 3: Verify (verifier doesn't need FHE key)
        result = verify_fhe_receipt(fhe_receipt)
    """
    fhe_proof = generate_fhe_stub_proof(envelope)

    return FHEReceipt(
        envelope_id=envelope.envelope_id,
        agent_id=envelope.agent_id,
        policy_hash=envelope.policy_hash,
        trace_length=envelope.trace_length,
        zk_receipt_ref=zk_receipt,
        fhe_proof=fhe_proof,
    )


# ---------------------------------------------------------------------------
# FHE Receipt Verification
# ---------------------------------------------------------------------------

def verify_fhe_receipt(fhe_receipt: FHEReceipt) -> dict:
    """
    Verify an FHE PACT receipt.

    Verification checks:
    1. Receipt structure is valid
    2. FHE proof is present and well-formed
    3. Policy hash is populated
    4. Trace commitment is consistent

    Note: In production, compliance_proof would be verified by a
    FHE-aware ZK verifier (Zama Concrete or RISC Zero with FHE extension).
    Stub proofs pass structural checks but are not cryptographically valid.

    Args:
        fhe_receipt: FHEReceipt instance or dict

    Returns:
        {"valid": bool, "reason": str, "policy_hash": str, "stub_warning": str}
    """
    if isinstance(fhe_receipt, dict):
        fhe_receipt = FHEReceipt(**fhe_receipt)

    # Structure checks
    if not fhe_receipt.receipt_id:
        return {"valid": False, "reason": "missing receipt_id"}
    if not fhe_receipt.policy_hash:
        return {"valid": False, "reason": "missing policy_hash in FHE receipt"}
    if fhe_receipt.trace_length < 0:
        return {"valid": False, "reason": "invalid trace_length"}

    fhe_proof = fhe_receipt.fhe_proof
    if not fhe_proof:
        return {"valid": False, "reason": "missing FHE proof in receipt"}

    # Proof type check
    if fhe_proof.proof_type != "fhe_membership":
        return {"valid": False, "reason": f"unknown proof type: {fhe_proof.proof_type}"}

    # Policy hash consistency
    if fhe_proof.policy_hash != fhe_receipt.policy_hash:
        return {
            "valid": False,
            "reason": "FHE proof policy_hash does not match receipt policy_hash",
        }

    # Trace commitment consistency
    if not fhe_proof.encrypted_trace_hash:
        return {"valid": False, "reason": "missing encrypted_trace_hash in FHE proof"}

    result = {
        "valid": True,
        "receipt_id": fhe_receipt.receipt_id,
        "policy_hash": fhe_receipt.policy_hash,
        "trace_length": fhe_receipt.trace_length,
        "proof_type": fhe_proof.proof_type,
        "fhe_params": fhe_proof.fhe_params,
    }

    if fhe_proof.stub:
        result["stub_warning"] = "STUB FHE proof — Zama Concrete or FHE prover not wired in. NOT for production."
        result["valid"] = True  # Structural validity only

    return result


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------

def fhe_receipt_to_dict(receipt: FHEReceipt) -> dict:
    """Serialize FHEReceipt to JSON dict."""
    return {
        "version": receipt.version,
        "receipt_id": receipt.receipt_id,
        "issued_at": receipt.issued_at,
        "envelope_id": receipt.envelope_id,
        "agent_id": receipt.agent_id,
        "policy_hash": receipt.policy_hash,
        "trace_length": receipt.trace_length,
        "zk_receipt_ref": receipt.zk_receipt_ref,
        "fhe_proof": {
            "proof_type": receipt.fhe_proof.proof_type,
            "fhe_params": receipt.fhe_proof.fhe_params,
            "encrypted_trace_hash": receipt.fhe_proof.encrypted_trace_hash,
            "policy_hash": receipt.fhe_proof.policy_hash,
            "compliance_proof": receipt.fhe_proof.compliance_proof,
            "stub": receipt.fhe_proof.stub,
        } if receipt.fhe_proof else None,
    }


def fhe_receipt_to_json(receipt: FHEReceipt, indent: Optional[int] = 2) -> str:
    """Serialize FHEReceipt to JSON string."""
    return json.dumps(fhe_receipt_to_dict(receipt), indent=indent)


def fhe_envelope_to_dict(envelope: FHEHistoryEnvelope) -> dict:
    """Serialize FHEHistoryEnvelope to JSON dict."""
    return {
        "version": envelope.version,
        "envelope_id": envelope.envelope_id,
        "created_at": envelope.created_at,
        "agent_id": envelope.agent_id,
        "policy_hash": envelope.policy_hash,
        "trace_length": envelope.trace_length,
        "ciphertext_hashes": envelope.ciphertext_hashes,
        "trace_commitment": envelope.trace_commitment,
        "fhe_params": envelope.fhe_params,
        "encrypted_metadata": envelope.encrypted_metadata,
    }


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

def demo():
    """Smoke test FHE receipt generation and verification."""
    print(f"PACT FHE Receipt v{PACT_FHE_VERSION}")
    print("=" * 50)

    # Simulate encrypted tool-call hashes (FHE ciphertexts)
    encrypted_hashes = [
        "fhe_ct_aabbccdd...",  # In production: real TFHE ciphertext strings
        "fhe_ct_eeff0011...",
        "fhe_ct_22334455...",
    ]
    policy_hash = "sha256:abc123def456abc123def456abc123def456abc123def456abc123def456abc1"
    agent_id = "did:key:z6MkTestAgent123"

    # Step 1: Build FHE envelope
    envelope = create_fhe_envelope(
        agent_id=agent_id,
        policy_hash=policy_hash,
        encrypted_tool_hashes=encrypted_hashes,
    )
    print(f"Envelope ID:   {envelope.envelope_id}")
    print(f"Trace length:  {envelope.trace_length}")
    print(f"Commitment:    {envelope.trace_commitment[:40]}...")
    print()

    # Step 2: Generate FHE receipt (with embedded v0.3 ZK receipt ref)
    mock_zk_receipt = {
        "receipt_id": "zk-receipt-001",
        "policy_hash": policy_hash,
        "outcome": "permitted",
    }
    fhe_receipt = generate_fhe_receipt(envelope, zk_receipt=mock_zk_receipt)
    print(f"Receipt ID:    {fhe_receipt.receipt_id}")
    print(f"Policy hash:   {fhe_receipt.policy_hash[:40]}...")
    print(f"ZK ref:        {fhe_receipt.zk_receipt_ref is not None}")
    print()

    # Step 3: Verify
    result = verify_fhe_receipt(fhe_receipt)
    status = "✓ PASS" if result["valid"] else "✗ FAIL"
    print(f"Verification:  {status} — {result['reason'] if 'reason' in result else 'OK'}")
    if "stub_warning" in result:
        print(f"Stub:         {result['stub_warning']}")
    print()

    # JSON output sample
    print("FHE Receipt JSON:")
    print(fhe_receipt_to_json(fhe_receipt)[:500])
    print()
    print("Composition: PACT v0.3 ZK receipt + FHE encrypted trace = full behavioral accountability")


if __name__ == "__main__":
    demo()
