"""
PACT v0.3 — Receipt Interface & SCITT Envelope Adapter

Defines the canonical PACT receipt structure and serializes it as a SCITT-compatible
signed statement. PTV draft (IETF draft-anandakrishnan-rats-ptv-agent-identity-00) explicitly
names SCITT composition for execution receipts — this module implements that interface.

Receipt Anatomy:
    1. Header: metadata, format version, algorithm suite
    2. Policy Commitment: policy_hash, log_index, log_id, merkle_root
    3. Tool Call Record: tool_name, tool_input_hash, timestamp, action_id
    4. ZK Proof: proof bytes (or DUMMY marker), image_id
    5. SCITT Envelope: cbor-encoded signed statement with payload type URN

Architecture:
    PACT receipt (Python/TypeScript)
        → to_scitt_envelope() → SCITT statement (CBOR)
        → sign(key) → SignedBundle
        → transparency_log.submit() → SCITT receipt (counter-signed log entry)

References:
    - IETF draft-anandakrishnan-rats-ptv-agent-identity-00 (PTV Protocol, Apr 2026)
    - IETF draft-ietf-scitt-architecture (SCITT Architecture)
    - RATS (Remote Attestation Procedures)
"""

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


# ---------------------------------------------------------------------------
# Receipt Version
# ---------------------------------------------------------------------------

PACT_RECEIPT_VERSION = "0.3.0"


# ---------------------------------------------------------------------------
# Core Receipt Types
# ---------------------------------------------------------------------------

@dataclass
class PolicyCommitment:
    """Layer 1: Policy commitment anchored to the transparency log."""
    policy_hash: str           # sha256:... of committed policy doc
    log_index: int            # Index in the transparency log
    log_id: str               # SHA-256(index | prev_hash | timestamp | merkle_root | policies)
    merkle_root: str          # Merkle root for this batch
    merkle_proof: list[dict]  # Inclusion proof: [{hash, side}, ...]


@dataclass
class ToolCall:
    """A single tool invocation record within a receipt."""
    tool_name: str            # e.g., "read_file", "search_web"
    tool_input_hash: str     # SHA-256 of serialized input args
    timestamp: str            # ISO-8601 UTC
    action_id: str           # Unique action UUID for this call
    tool_output_hash: Optional[str] = None  # SHA-256 of output (if included)


@dataclass
class ZKProof:
    """Zero-knowledge proof generated by the RISC Zero prover (or DUMMY)."""
    proof_type: str           # "risc0" | "dummy"
    image_id: str             # Image ID of the committed guest program
    seal: str                 # Raw seal bytes (or DUMMY marker when DUMMY_PROOF=1)
    public_inputs: dict      # {policy_hash, merkle_root, log_index, tool_name_hash, timestamp}


@dataclass
class PACTReceipt:
    """
    Canonical PACT receipt structure.

    A receipt proves that an agent's tool call was authorized under a committed
    policy at a specific point in time, without revealing the policy or inputs
    to parties other than the verifier.

    The receipt is self-contained: any party can verify policy membership using
    the embedded anchor + proof without consulting the transparency log directly.
    """
    version: str = PACT_RECEIPT_VERSION
    receipt_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    issued_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    policy: PolicyCommitment = field(default_factory=lambda: PolicyCommitment(
        policy_hash="", log_index=0, log_id="", merkle_root="", merkle_proof=[]
    ))
    tool_call: ToolCall = field(default_factory=lambda: ToolCall(
        tool_name="", tool_input_hash="", timestamp="", action_id=""
    ))
    proof: Optional[ZKProof] = None  # None = statement-only receipt (no ZK yet)


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------

def create_receipt(
    policy_commitment: PolicyCommitment,
    tool_call: ToolCall,
    proof: Optional[ZKProof] = None,
) -> PACTReceipt:
    """Factory: build a complete PACT receipt."""
    return PACTReceipt(
        policy=policy_commitment,
        tool_call=tool_call,
        proof=proof,
    )


def receipt_to_dict(receipt: PACTReceipt) -> dict:
    """Serialize a PACT receipt to a JSON-serializable dict."""
    return {
        "version": receipt.version,
        "receipt_id": receipt.receipt_id,
        "issued_at": receipt.issued_at,
        "policy": {
            "policy_hash": receipt.policy.policy_hash,
            "log_index": receipt.policy.log_index,
            "log_id": receipt.policy.log_id,
            "merkle_root": receipt.policy.merkle_root,
            "merkle_proof": receipt.policy.merkle_proof,
        },
        "tool_call": {
            "tool_name": receipt.tool_call.tool_name,
            "tool_input_hash": receipt.tool_call.tool_input_hash,
            "timestamp": receipt.tool_call.timestamp,
            "action_id": receipt.tool_call.action_id,
            "tool_output_hash": receipt.tool_call.tool_output_hash,
        },
        "proof": {
            "proof_type": receipt.proof.proof_type,
            "image_id": receipt.proof.image_id,
            "seal": receipt.proof.seal,
            "public_inputs": receipt.proof.public_inputs,
        } if receipt.proof else None,
    }


def receipt_to_json(receipt: PACTReceipt, indent: Optional[int] = None) -> str:
    """Serialize a PACT receipt to a JSON string."""
    return json.dumps(receipt_to_dict(receipt), indent=indent)


def receipt_from_dict(d: dict) -> PACTReceipt:
    """Deserialize from a JSON dict."""
    return PACTReceipt(
        version=d.get("version", PACT_RECEIPT_VERSION),
        receipt_id=d.get("receipt_id", str(uuid.uuid4())),
        issued_at=d.get("issued_at", ""),
        policy=PolicyCommitment(
            policy_hash=d["policy"]["policy_hash"],
            log_index=d["policy"]["log_index"],
            log_id=d["policy"]["log_id"],
            merkle_root=d["policy"]["merkle_root"],
            merkle_proof=d["policy"]["merkle_proof"],
        ),
        tool_call=ToolCall(
            tool_name=d["tool_call"]["tool_name"],
            tool_input_hash=d["tool_call"]["tool_input_hash"],
            timestamp=d["tool_call"]["timestamp"],
            action_id=d["tool_call"]["action_id"],
            tool_output_hash=d["tool_call"].get("tool_output_hash"),
        ),
        proof=ZKProof(
            proof_type=d["proof"]["proof_type"],
            image_id=d["proof"]["image_id"],
            seal=d["proof"]["seal"],
            public_inputs=d["proof"]["public_inputs"],
        ) if d.get("proof") else None,
    )


# ---------------------------------------------------------------------------
# Tool Call Hashing Utilities
# ---------------------------------------------------------------------------

def hash_tool_inputs(tool_name: str, args: dict) -> str:
    """Compute deterministic SHA-256 of tool inputs for non-repudiation."""
    canonical = json.dumps({"tool": tool_name, "args": args}, sort_keys=True, separators=(",", ":"))
    return f"sha256:{hashlib.sha256(canonical.encode('utf-8')).hexdigest()}"


def hash_tool_output(output: str) -> str:
    """Compute SHA-256 of tool output for inclusion in receipt."""
    return f"sha256:{hashlib.sha256(output.encode('utf-8')).hexdigest()}"


# ---------------------------------------------------------------------------
# SCITT Envelope Adapter
# ---------------------------------------------------------------------------
# Per PTV draft: receipts are composed with SCITT for cross-party verification.
# SCITT = Supply Chain Integrity, Transparency and Trust
# Spec: https://github.com/ietf-scitt/draft-ietf-scitt-architecture
#
# SCITT statements are CBOR-encoded signed envelopes.
# Payload type URN for PACT receipts: "urn:pact:receipt:v0.3"
#
# The SCITT envelope structure:
#   {
#     "statement": <cbor_encoded(PACT_receipt)>,
#     "payload_type": "urn:pact:receipt:v0.3",
#     "signing_time": <ISO-8601>,
#     "issuer": <did:key of signing entity>,
#   }
# ---------------------------------------------------------------------------

SCITT_PAYLOAD_TYPE = "urn:pact:receipt:v0.3"

# These URNs match the PTV draft naming for RATS-compatible attestations
_PACT_PAYLOAD_TYPES = {
    "0.3": "urn:pact:receipt:v0.3",
    "action": "urn:pact:action-record:v1",
}


def build_scitt_statement(receipt: PACTReceipt) -> dict:
    """
    Build a SCITT-compatible statement dict from a PACT receipt.

    The statement is the payload of the SCITT signed envelope.
    In production this would be CBOR-encoded; here we use the Python dict
    as an intermediate representation that can be CBOR-serialized.

    PTV draft alignment:
    - payload_type identifies this as a PACT receipt
    - statement contains the full action record
    - issuer DID is recorded for verifier lookup
    """
    receipt_dict = receipt_to_dict(receipt)

    return {
        "statement": receipt_dict,
        "payload_type": SCITT_PAYLOAD_TYPE,
        "signing_time": datetime.now(timezone.utc).isoformat(),
        "issuer": receipt_dict["issued_at"],  # Placeholder; real impl uses did:key
        "receipt_format": "pact-v{}".format(receipt.version),
    }


def verify_scitt_envelope(statement: dict) -> dict:
    """
    Verify a SCITT envelope deserializes to a valid PACT receipt.

    Returns a dict with:
        - valid: bool
        - receipt: PACTReceipt (if valid)
        - reason: str

    Note: Signature verification requires the issuer's DID document and
    must be performed by the SCITT transparency log service. This function
    only validates structure and type alignment.
    """
    payload_type = statement.get("payload_type", "")
    if payload_type != SCITT_PAYLOAD_TYPE:
        return {
            "valid": False,
            "reason": f"Unknown payload type: {payload_type}",
            "receipt": None,
        }

    receipt_dict = statement.get("statement")
    if not receipt_dict:
        return {"valid": False, "reason": "Missing statement field", "receipt": None}

    try:
        receipt = receipt_from_dict(receipt_dict)
    except Exception as e:
        return {"valid": False, "reason": f"Failed to deserialize receipt: {e}", "receipt": None}

    return {
        "valid": True,
        "reason": "SCITT envelope structure valid",
        "receipt": receipt,
        "receipt_id": receipt.receipt_id,
    }


# ---------------------------------------------------------------------------
# Demo / Smoke Test
# ---------------------------------------------------------------------------

def demo():
    """Smoke test the receipt interface."""
    print(f"PACT Receipt v{PACT_RECEIPT_VERSION}")
    print("=" * 50)

    # Build a mock receipt
    policy_commitment = PolicyCommitment(
        policy_hash="sha256:aabbccdd...",
        log_index=0,
        log_id="sha256:genesis001",
        merkle_root="sha256:merkleroot001",
        merkle_proof=[{"hash": "sha256:sibling1", "side": "right"}],
    )

    tool_call = ToolCall(
        tool_name="read_file",
        tool_input_hash=hash_tool_inputs("read_file", {"path": "/tmp/test"}),
        timestamp=datetime.now(timezone.utc).isoformat(),
        action_id=str(uuid.uuid4()),
        tool_output_hash=None,
    )

    proof = ZKProof(
        proof_type="dummy",
        image_id="pact-guest-v0.3",
        seal="DUMMY_PROOF",
        public_inputs={
            "policy_hash": policy_commitment.policy_hash,
            "merkle_root": policy_commitment.merkle_root,
            "log_index": 0,
            "tool_name_hash": "sha256:placeholder",
            "timestamp": tool_call.timestamp,
        },
    )

    receipt = create_receipt(policy_commitment, tool_call, proof)
    print(f"Receipt ID: {receipt.receipt_id}")
    print(f"Tool: {receipt.tool_call.tool_name}")
    print(f"Policy hash: {receipt.policy.policy_hash[:20]}...")
    print()

    # Serialize
    json_str = receipt_to_json(receipt, indent=2)
    print("JSON serialization:")
    print(json_str[:300])
    print()

    # SCITT envelope
    scitt = build_scitt_statement(receipt)
    print("SCITT statement payload_type:", scitt["payload_type"])
    print()

    # Verify
    result = verify_scitt_envelope(scitt)
    print("SCITT verification:", "✓ PASS" if result["valid"] else "✗ FAIL", "—", result["reason"])
    print()


if __name__ == "__main__":
    demo()
